server {
    listen 80;
    server_name lukin.blog;
    server_name www.lukin.blog;

    location / {
        return 301 https://lukin.blog$request_uri;
    }
}

server {
    listen 443 ssl;
    http2 on;
    server_name www.lukin.blog;

    ssl_certificate /etc/letsencrypt/live/lukin.blog/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/lukin.blog/privkey.pem;

    location / {
        return 301 https://lukin.blog$request_uri;
    }
}

server {
    listen 443 ssl;
    server_name lukin.blog;
    http2 on;

    charset utf-8;
    index index.php;
    root /srv/http/lukin.blog/wordpress;

    ssl_certificate /etc/letsencrypt/live/lukin.blog/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/lukin.blog/privkey.pem;

    location = /favicon.ico {
        log_not_found off;
        access_log off;
    }

    location = /robots.txt {
        log_not_found off;
        access_log off;
    }

    location = /xmlrpc.php {
        deny all;
    }

    location = /wp-config.php {
        deny all;
    }

    location ~* /(?:uploads|files)/.*\.php$ {
        deny all;
    }

    location ~ /\. {
        deny all;
    }

    location ~* \.(js|css|png|jpg|jpeg|gif|ico)$ {
        expires max;
        log_not_found off;
    }

    location ~* \.php$ {
        try_files $uri =404;

        include fastcgi.conf;

        fastcgi_index index.php;
        fastcgi_pass unix:/var/run/php/php8.4-fpm.sock;
    }

    location / {
        try_files $uri $uri/ /index.php?$args;
    }

    location = /relocate/ {
        include fastcgi.conf;

        fastcgi_param  SCRIPT_FILENAME /srv/http/lukin.blog/relocate/index.php;
        fastcgi_pass unix:/var/run/php/php8.4-fpm.sock;
    }
}
